### ISSUE TITLE
Populate beneficiaries from API?

### ISSUE THREAD

**Issue by kellywu** [pic-development/insureio-public#1]
Hi, I'd like to populate the beneficiaries section of the Online Application. How can I do this through the [Lead Import API](http://wiki.dataraptor.com/index.php/Lead_Import)?

The beneficiaries section I'm talking about is under https://pinney.dataraptor.com/quoting/quotes/new#?client_id=[some_client_id] > **Application panel**
![screen shot 2015-04-29 at 9 00 02 am](https://cloud.githubusercontent.com/assets/740302/7391335/643dc296-ee4e-11e4-96ab-adcbdde4a09d.png)

Thanks!

@entrity

**Comment by maurice-does-software** [comment]
I have updated our documentation so that it now covers adding beneficiaries via the API endpoint. Relevant sections are http://wiki.dataraptor.com/index.php/Lead_Import#Beneficiary and http://wiki.dataraptor.com/index.php/Lead_Import#Example.
