### ISSUE TITLE
Cannot delete existing consumers through API

### ISSUE THREAD

**Issue by kellywu** [pic-development/insureio-public#3]
I'm trying to delete existing consumers through a DELETE request to https://pinney.dataraptor.com/crm/connections/[some_consumer_id].json

I use the same Headers as I use to successfully make a post request. However, I am getting a **401 Unauthorized** response. Any thoughts?

@entrity

**Comment by maurice-does-software** [comment]
@kellywu what content, if any, do you receive in the response _body_? A quick look at the code on our end seems to indicate that a 401 response should only occur if you are trying to delete a consumer which would normally not be viewable to your user account.

It would help us to more efficiently troubleshoot this issue if you could provide either a sample request and the response, or simply a user account id with which you were logged in and an id of a consumer which you tried to delete when you got the 401 response.
