### ISSUE TITLE
Quoter widget name/phone/email fields won't disappear

### ISSUE THREAD

**Issue by entrity** [pic-development/insureio-public#4]
Chris Huntley says:

> Hey Markham/Nic,
> I’m having an issue making the full name/phone/email fields disappear from the form.  I uncheck them and nothing happens.  Am I doing something wrong?

**Comment by maurice-does-software** [comment]
It appears the issue was a lack of immediate feedback in the form. Changing those checkboxes would indeed save properly and hide the indicated fields in the generated widget, just not in the preview.
